### ISSUE TITLE
Library not manually updating default library

### ISSUE THREAD

**Issue by fedex-bermu** [null2264/yokai#180] opened 2024-09-01 21:32 UTC
### Steps to reproduce

Swipe down to update on the default library

### Expected behavior

Library should update

### Actual behavior

Nothing happens

### Yōkai version

App version: 1.8.5.6-r5683 (standard, 1925a503d, 147, 2024-09-01T03:36:35Z)

### Android version

Android version: 14 (SDK 34)

### Device

Samsung SM-S918B (dm3q)

### Other details

If you try the same thing on other categories it updates that category. 
![Screenshot_20240901_183129_Ykai](https://github.com/user-attachments/assets/dd72ff40-9b92-4567-8c8d-c57f9266a686)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by fedex-bermu** [comment] 2024-09-02 01:36
`App version: 1.8.5.6 (standard, 2debbc0a1, 147, 2024-08-25T12:32:48Z)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007.S918BXXS6CXG8
Device brand: samsung
Device manufacturer: samsung
Device name: dm3q
Device model: SM-S918B
Device product name: dm3qxxx



--------- beginning of main
09-01 22:27:40.896 26839 26896 E FrameEvents: updateAcquireFence: Did not find frame.
09-01 22:27:42.886 26839 26912 E SQLiteLog: (284) automatic index on split(_id)
09-01 22:33:24.618 26839 25017 E         : Extension package is not found (com.tortel.syslog)
09-01 22:34:13.382 26839 17529 E         : Extension package is not found (com.tananaev.logcat)
09-01 22:34:46.917 25177 25177 E tachiyomi.yokai: Not starting debugger since process cannot load the jdwp agent.
09-01 22:34:47.084 25177 25226 E tachiyomi.yokai: No package ID 79 found for resource ID 0x790b000f.
09-01 22:34:47.084 25177 25226 E tachiyomi.yokai: No package ID 79 found for resource ID 0x790b000f.
09-01 22:34:47.167 25177 25229 E SQLiteLog: (283) recovered 72 frames from WAL file /data/data/eu.kanade.tachiyomi.yokai/databases/tachiyomi.db-wal
09-01 22:34:47.546 25177 25254 E SQLiteLog: (284) automatic index on split(_id)
09-01 22:34:49.476 25177 25257 E SQLiteLog: (284) automatic index on S(manga_id)`

**Comment by fedex-bermu** [comment] 2024-10-06 23:27
Is there anything I can do to help solve this problem?  I'm not trying to rush this, but maybe a there is a way to have a more detailed log or something

**Comment by null2264** [comment] 2024-10-07 00:24
I haven't actually look into it just yet due to irl stuff so I only been troubleshooting bugs that has much clearer root cause lately, but I'm guessing the default category is accidentally filtered out from manual update somehow.

**Comment by null2264** [comment] 2024-12-08 03:38
Fixed on https://github.com/null2264/yokai/commit/349b9c181aa2dccbff10701a11b022861691b6ef

**Closed by null2264** 2024-12-08 03:38 UTC
Labels: bug
