### ISSUE TITLE
Reset scanlator filter doesn't work

### ISSUE THREAD

**Issue by paressz** [null2264/yokai#237] opened 2024-11-07 18:41 UTC
### Steps to reproduce

1. Filter scanlator from the chapter list
2. Manually remove all or reset the filter
3. Navigate to library 
4. Navigate to the manga page
5. Filter is back

### Expected behavior

Resetting scanlator filter should show all available chapters from all scanlator after opening the manga page again.

### Actual behavior

Resetting scanlator filter only shows all available chapters if I didn't leave the manga page, but clicking on the chapter shows an error. Leaving the manga page will bring the previous filter back

### Yōkai version

1.8.5.9

### Android version

Android 14

### Device

Poco x5

### Other details

It only happens if the filter is emptied.

This is the error message after clicking on a chapter after removing the scanlator from filter without leaving the manga page:
https://imgur.com/a/csRfcWI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment] 2024-11-08 00:35
Duplicate of GH-228.

You can add your details there...

**Closed by null2264** 2024-11-08 00:35 UTC
Labels: bug
