### ISSUE TITLE
Crash when exiting a Manga

### ISSUE THREAD

**Issue by MrDfour** [null2264/yokai#235] opened 2024-10-30 06:04 UTC
### Steps to reproduce

Read Manga
Reach final page of said chapter, next chapter available and downloaded
Press the back button, the cellphone one
Crash

### Expected behavior

Shouldn't crash

### Actual behavior

Crashes

### Crash logs

![Screenshot_2024-10-30-00-01-30-964_eu kanade tachiyomi yokai](https://github.com/user-attachments/assets/f5d8a0ae-7b3e-4c06-84b6-566f666e4903)
App version: 1.8.5.9 (standard, 4b46e9a02, 149, 2024-10-06T09:14:12Z)
Android version: 14 (SDK 34)
Android build ID: UP1A.230905.011
Device brand: POCO
Device manufacturer: Xiaomi
Device name: duchamp
Device model: 2311DRK48G
Device product name: duchamp_global

java.lang.Throwable: java.lang.IllegalStateException: Check failed.
	at eu.kanade.tachiyomi.ui.reader.loader.ArchivePageLoader.loadPage(SourceFile:18)
	at eu.kanade.tachiyomi.ui.reader.loader.DownloadPageLoader.loadPage(SourceFile:5)
	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerPageHolder$launchLoadJob$1.invokeSuspend(SourceFile:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:92)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8658)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@39f95a2, Dispatchers.Main]

--------- beginning of main
10-29 23:54:21.323 19832 24343 E OpenGLRenderer: Unable to match the desired swap behavior.
10-29 23:54:27.072 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.076 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.083 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.093 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.102 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.109 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.117 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.126 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.133 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.142 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.150 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.159 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.167 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.175 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.183 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.192 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.201 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.210 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.217 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.226 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.234 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.243 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.251 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:27.258 19832 24768 E Surface : IGraphicBufferProducer::setMaxDequeuedBufferCount(2) returned Invalid argument
10-29 23:54:27.259 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:28.248 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:28.256 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:28.265 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:28.272 19832 24768 E Surface : IGraphicBufferProducer::setMaxDequeuedBufferCount(2) returned Invalid argument
10-29 23:54:28.272 19832 24343 E BLASTBufferQueue: [VRI[MainActivity]#18](f:1,a:4) acquireNextBufferLocked: Can't acquire next buffer. Already acquired max frames 4 max:2 + 2
10-29 23:54:37.470 19832 19832 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation.
10-29 23:54:37.474 19832 24343 E FrameEvents: updateAcquireFence: Did not find frame.
10-29 23:54:37.581 19832 24343 E OpenGLRenderer: Unable to match the desired swap behavior.
10-30 00:00:10.605 19832 19832 E         : Something went wrong!
10-30 00:00:10.605 19832 19832 E         : java.lang.IllegalStateException: Check failed.
10-30 00:00:10.605 19832 19832 E         : 	at eu.kanade.tachiyomi.ui.reader.loader.ArchivePageLoader.loadPage(SourceFile:18)
10-30 00:00:10.605 19832 19832 E         : 	at eu.kanade.tachiyomi.ui.reader.loader.DownloadPageLoader.loadPage(SourceFile:5)
10-30 00:00:10.605 19832 19832 E         : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerPageHolder$launchLoadJob$1.invokeSuspend(SourceFile:33)
10-30 00:00:10.605 19832 19832 E         : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
10-30 00:00:10.605 19832 19832 E         : 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:92)
10-30 00:00:10.605 19832 19832 E         : 	at android.os.Handler.handleCallback(Handler.java:958)
10-30 00:00:10.605 19832 19832 E         : 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 00:00:10.605 19832 19832 E         : 	at android.os.Looper.loopOnce(Looper.java:222)
10-30 00:00:10.605 19832 19832 E         : 	at android.os.Looper.loop(Looper.java:314)
10-30 00:00:10.605 19832 19832 E         : 	at android.app.ActivityThread.main(ActivityThread.java:8658)
10-30 00:00:10.605 19832 19832 E         : 	at java.lang.reflect.Method.invoke(Native Method)
10-30 00:00:10.605 19832 19832 E         : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
10-30 00:00:10.605 19832 19832 E         : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
10-30 00:00:10.605 19832 19832 E         : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@39f95a2, Dispatchers.Main]
10-30 00:00:10.736 14856 14856 E i:error_handler: Not starting debugger since process cannot load the jdwp agent.
10-30 00:00:10.815 14856 17809 E QT      : [QT]file does not exist
10-30 00:00:10.826 14856 17809 E libMiGL : libmigl:This GPU version is note support Variable Shading Rate
10-30 00:00:10.828 14856 17809 E libEGL  : pre_cache appList: ,,
10-30 00:00:10.984 14856 17803 E SQLiteLog: (283) recovered 96 frames from WAL file /data/data/eu.kanade.tachiyomi.yokai/databases/tachiyomi.db-wal
10-30 00:00:11.620 17872 17872 E tachiyomi.yokai: Not starting debugger since process cannot load the jdwp agent.
10-30 00:00:11.751 17872 17922 E tachiyomi.yokai: No package ID 77 found for resource ID 0x770b000f.
10-30 00:00:11.751 17872 17922 E tachiyomi.yokai: No package ID 77 found for resource ID 0x770b000f.
10-30 00:00:11.849 17872 17931 E chromium: [1030/000011.846282:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
10-30 00:00:12.069 14856 17809 E OpenGLRenderer: Unable to match the desired swap behavior.
10-30 00:00:12.146 14856 17809 E LB      : fail to open file: No such file or directory
10-30 00:00:12.146 14856 17809 E LB      : fail to open node: No such file or directory
10-30 00:00:12.152 17872 17904 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
10-30 00:00:56.544 14856 17809 E OpenGLRenderer: Unable to match the desired swap behavior.

### Yōkai version

1.8.5.9

### Android version

Android 14

### Device

Poco X6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by MrDfour** [comment] 2024-10-30 06:06
Unable to reproduce crash again, BTW. It seems a one time case

**Comment by null2264** [comment] 2024-12-12 04:30
Duplicate of GH-170

> Unable to reproduce crash again, BTW. It seems a one time case

I'll keep GH-170 open just in case.

**Closed by null2264** 2024-12-12 04:30 UTC
Labels: bug
