### ISSUE TITLE
Not able to put a manga in multiple categories; may persist even after restoring backup(?)

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#83] opened 2024-06-07 03:08 UTC
### Steps to reproduce

Update to the previous release of 1.8.3.4-b5175 (I don't remember exactly how was the version numer of it but it's the one before that)
Search for [manga] that was in category ** and **** before updating

### Expected behavior

Should show [manga] in both categories

### Actual behavior

It shows [manga] in just one category and with its added date changed (it appears as if it was added to the library months ago when actually it was just some days ago) I have a theory that it replaces another [manga]

### Yōkai version

1.8.3.4-b5175 and previous

### Android version

Android 12

### Device

Samsung S10+

### Other details

Since it only happened when updating the app, maybe it's a bug about that specifically

When checking which categories [manga] is in (when opening this icon from the library; and inside the manga)
![Screenshot_20240606_202701_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/f19e9d5b-c64e-4cfc-bb1c-a8204c997521)
it appears that [manga] is selected to be in both categories, but it is not visible in the library

Even if I delete [manga] in its entirety from the library and add it again to change its date of addition and the categories where it should be, it does not change until later, but in only appears in one category anyway

I know the solution to this could be backup, but, restoration is slow ASF, at least for me, maybe because I have a lot of manga in my library. It's also the reason why I don't move to Stable Build anymore. And, even though I already have a backup from a day ago, apart from the fact that the restore is especially slow, I'm afraid that it will change new information like chapters read (an addition to the library; that could change)
It would be great to have an answer to that latter, but (again), the problem of categories could persist anyway, though it'd fix it for me this one time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.3.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment] 2024-06-07 03:52
I think that fixed it, try latest nightly version

**Comment by lalalasupa0** [comment] 2024-06-07 04:09
> I think that fixed it, try latest nightly version

Yup, it's fixed. But the added date is still messed up though... And I lost an edited description trying to fix that for one 😵

Should an issue about this be opened? ; that "removing" a manga shouldn't restore the edit of its description, or that it should return to the edited one when adding the manga again)

Idk if I should clode this

**Comment by null2264** [comment] 2024-06-07 06:09
> that it should return to the edited one when adding the manga again

Wait, unfavouriting an entry not supposed to clear edits? I swear that's a J2K normal behaviour :thinking:

> But the added date is still messed up though

Haven't figure out what happened here

**Comment by lalalasupa0** [comment] 2024-06-07 06:21
> > that it should return to the edited one when adding the manga again
> 
> Wait, unfavouriting an entry not supposed to clear edits? I swear that's a J2K normal behaviour 🤔
> 
> > But the added date is still messed up though
> 
> Haven't figure out what happened here

Just for specifications ~
> unfavouriting an entry not supposed to clear edits

When removing a manga with an edited description, the edited description is restored to the one on the web, thus losing the one edited by you, it happened to me with the manhwa "Perfect Half" in the Bato (Eng) source

> Haven't figure out what happened here

When I entered the app already updated, some entries (more than 3 that I have yet to discover) went to the bottom, when they should be at the top (in order of date of addition to the library)

**Comment by null2264** [comment] 2024-06-07 06:36
> When removing a manga with an edited description, the edited description is restored to the one on the web, thus losing the one edited by you, it happened to me with the manhwa "Perfect Half" in the Bato (Eng) source

Yeah, that's intended behaviour from J2K (afaik)

**Comment by null2264** [comment] 2024-06-07 07:08
> When I entered the app already updated, some entries (more than 3 that I have yet to discover) went to the bottom, when they should be at the top (in order of date of addition to the library)

Just tested with my backup, seems to be working fine, could be a rare bug.

Closing this issue since it is no longer related to the initial issue, if the issue persist feel free to open a new issue :+1:

**Closed by null2264** 2024-06-07 07:08 UTC
Labels: bug
