### ISSUE TITLE
Feature request that they will probably reject XD.

### ISSUE THREAD

**Issue by FrankieD777** [null2264/yokai#196] opened 2024-09-20 13:25 UTC
### Describe your suggested feature

The functionality is simple to describe but more complex to implement. It would be appropriate to add the option for advanced recommendations; that is, when accessing a manga, the system automatically suggests similar content within the same context or scope of the publication, without the need to collect user data.

### Other details

I have decided to make this request because of my experience with different manga applications on mobile devices. On my previous phone, I used to use an app called Komikku, which I really found phenomenal. I greatly enjoyed its interface and especially its recommendation feature, which helped me considerably in discovering new titles and enjoying varied readings without having to spend too much time searching on my own.

However, I recently had the opportunity to try a new app called Yokai, and I must say that I was pleasantly surprised. From its more refined design to its optimized performance, Yokai quickly earned a special place in my heart and won me over to the point of becoming my favorite app for reading manga. I find that the user experience is notably superior and tailored to my needs, which is something I truly value.

Despite all the advantages Yokai offers, there is one element of Komikku that I still miss a lot: its recommendation system. This particular feature was an incredibly useful tool for me, as it provided personalized suggestions based on my preferences and reading habits, making it easy for me to discover new manga effortlessly. It is that specific functionality that I feel is missing in Yokai for my experience to be even more complete and satisfying.

That is why I would like to propose the idea of incorporating a recommendation feature in the Yokai app. I am convinced that this addition would not only enhance the user experience but also reinforce Yokai's position as the best manga app on the market. As an avid reader and admirer of the platform, I sincerely hope that my suggestion will be considered, as I am sure many other users would greatly appreciate this feature. Thank you for your attention and for developing such an amazing app. :3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment] 2024-09-27 00:45
Duplicate of GH-93

**Comment by null2264** [comment] 2024-09-27 00:45
If you have anything to add, feel free to reply to that issue instead.

**Closed by null2264** 2024-09-27 00:45 UTC
Labels: enhancement
