### ISSUE TITLE
No sé puede leer por paginado

### ISSUE THREAD

**Issue by Unknoweird** [null2264/yokai#32] opened 2024-02-11 17:27 UTC
### Steps to reproduce

1. Busco cualquier manga o comic que tenga como opción de lectura de paginado de izquierda a derecha o derecha a izquierda 

### Expected behavior

Leer cualquier manga o comic deslizando a la izquierda o derecha 

### Actual behavior

Todas las páginas están en blanco o negro  a menos que lo tenga en vista horizonte o longtrip

### Yōkai version

Yõkai v1.7.13

### Android version

Android 10

### Device

Moto E6i

### Other details

Esto pasó desde la última actualización de Yõkai (no sean tan trolls como antes jaja)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.13](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by mechagomizilla** [comment] 2024-02-11 20:43
From what I can gather (sorry, I don't speak your language), this is a duplicate of issue #25. https://github.com/null2264/yokai/issues/25

**Comment by null2264** [comment] 2024-02-12 00:10
Duplicate of GH-25, for now you can workaround it by disabling "Show content in cutout area". Also, please use English in the future.

**Closed by null2264** 2024-02-12 00:10 UTC
Labels: bug
