### ISSUE TITLE
Estimated Time like Mihon

### ISSUE THREAD

**Issue by Nihal621** [null2264/yokai#140] opened 2024-08-08 01:40 UTC
### Describe your suggested feature

Mihon has a feature of estimated time of every entries where it shows the estimated timing of when the new chapters would be released.  My request is to bring this amazing feature to Yokai too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.4.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment] 2024-08-08 04:33
Duplicate of GH-53, it will be added when smart update is added.

**Closed by null2264** 2024-08-08 04:33 UTC
Labels: enhancement

**Comment by Nihal621** [comment] 2024-08-08 04:46
> Duplicate of [GH-53](https://github.com/null2264/yokai/issues/53), it will be added when smart update is added as it depends on it.

So will you ppl add smart update?

**Comment by null2264** [comment] 2024-08-08 23:49
It is planned
