### ISSUE TITLE
Chapter Duplicate 

### ISSUE THREAD

**Issue by Recri97** [null2264/yokai#306] opened 2024-12-14 06:19 UTC
### Steps to reproduce

Search entries
Some source load duplicate chapter , i believe the source it's not the problem because while I checked webview mode theres no duplicate 

### Expected behavior

Chapter load normaly 
![Screenshot_2024-12-14-12-50-05-049_eu kanade tachiyomi yokai](https://github.com/user-attachments/assets/bea24bce-3e33-43d7-9f83-5a3804116c8d)

### Actual behavior

Chapter get duplicated
![Screenshot_2024-12-14-12-50-24-122_eu kanade tachiyomi yokai](https://github.com/user-attachments/assets/2edc4495-9a9c-42d3-bffa-e39014f188fd)

### Yōkai version

1.9.3

### Android version

Android 11

### Device

Redmi Note 8

### Other details

I Tried 2 different entries and 5 different source , results are 3 source chapter get duplicate, 2 normal 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment] 2024-12-14 06:40
Can you try refreshing it? maybe that could "fix"

Also, duplicate of GH-152, I could never replicate the issue unfortunately

**Closed by null2264** 2024-12-14 06:40 UTC
Labels: bug

**Comment by Recri97** [comment] 2024-12-14 07:02
> Can you try refreshing it? maybe that could "fix"
> 
> Also, duplicate of [GH-152](https://github.com/null2264/yokai/issues/152), I could never replicate the issue unfortunately

Nope ,Still same

https://github.com/user-attachments/assets/53866790-7810-4e76-9c92-60c5bcca51c2

**Comment by null2264** [comment] 2024-12-14 07:04
Hmm, alright, I'll figure something out later, go to GH-152 if you have any more input :+1:
