### ISSUE TITLE
Double chapter 

### ISSUE THREAD

**Issue by Kunaguero110** [null2264/yokai#308] opened 2024-12-16 11:29 UTC
### Steps to reproduce

![Screenshot_20241216-181602](https://github.com/user-attachments/assets/46895834-b8c1-4966-8aa2-f669397f9efe)

### Expected behavior

![Screenshot_20241216-182723](https://github.com/user-attachments/assets/c160646a-b80c-490d-aeb9-9310a0faa4a5)

### Actual behavior

some comic titles have double chapters

### Yōkai version

1.9.4

### Android version

Android 10

### Device

Redmi Note 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-12-16 11:43
Duplicate of #152

**Closed** 2024-12-16 11:44 UTC
Labels: bug
