### ISSUE TITLE
stuck in splash & random crash after update

### ISSUE THREAD

**Issue by m-a-hannan** [null2264/yokai#79] opened 2024-06-04 06:21 UTC
### Steps to reproduce

1. open the app
2. try to download something 

issue: stuck in splash screen or blank screen

![yokai stuck in splash or blank screen after update](https://github.com/null2264/yokai/assets/28342175/44b03be5-18c2-4468-8097-467056b9b619)

### Expected behavior

App will open and show the library, and download the selected chapter.

### Actual behavior

stuck in splash screen or blank screen, crashes when download button is selected.

### Crash logs

App version: 1.8.2 (standard, d0712bde7, 129, 2024-06-03T06:51Z)
Android version: 11 (SDK 30)
Android build ID: RMX1901_11_F.06
Device brand: Realme
Device manufacturer: Realme
Device name: RMX1901CN
Device model: RMX1901
Device product name: RMX1901

--------- beginning of system
06-04 17:46:36.744 26632 26632 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
06-04 17:51:57.061 26632 26632 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (29757) crash detected (code -1).
06-04 17:52:27.254 26632 26632 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (31495) crash detected (code -1).
06-04 17:52:41.965 26632 27571 E libEGL  : Invalid file path for libcolorx-loader.so
06-04 17:52:46.198 26632 32191 E Palette : Exception thrown during async generate
06-04 17:52:46.198 26632 32191 E Palette : java.lang.IllegalStateException: unable to getPixels(), pixel access is not supported on Config#HARDWARE bitmaps
06-04 17:52:46.198 26632 32191 E Palette : 	at android.graphics.Bitmap.checkHardware(Bitmap.java:445)
06-04 17:52:46.198 26632 32191 E Palette : 	at android.graphics.Bitmap.getPixels(Bitmap.java:2014)
06-04 17:52:46.198 26632 32191 E Palette : 	at androidx.palette.graphics.Palette$Builder.generate(SourceFile:3)
06-04 17:52:46.198 26632 32191 E Palette : 	at androidx.palette.graphics.Palette$Builder$1.doInBackground(SourceFile:5)
06-04 17:52:46.198 26632 32191 E Palette : 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
06-04 17:52:46.198 26632 32191 E Palette : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-04 17:52:46.198 26632 32191 E Palette : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-04 17:52:46.198 26632 32191 E Palette : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-04 17:52:46.198 26632 32191 E Palette : 	at java.lang.Thread.run(Thread.java:923)
06-04 17:52:49.042 32214 32214 E i:error_handle: Unknown bits set in runtime_flags: 0x40000000
06-04 17:52:49.048 32214 32214 E i:error_handle: Not starting debugger since process cannot load the jdwp agent.
06-04 17:52:49.052 32214 32214 E RefClass: java.lang.reflect.InvocationTargetException
06-04 17:52:49.078 32214 32214 E libc    : Access denied finding property "ro.odm.prev.product.name"
06-04 17:52:49.097 32214 32214 E Perf    :  perftest packageName : eu.kanade.tachiyomi.yokai Restructing the HIDE apis access to this app, App is not allowed to use Hide APIs :
06-04 17:52:49.187 32214 32240 E libEGL  : Invalid file path for libcolorx-loader.so
06-04 17:52:50.769 32214 32238 E libEGL  : Invalid file path for libcolorx-loader.so
06-04 17:52:50.776 32214 32238 E libEGL  : Invalid file path for libcolorx-loader.so
06-04 17:52:50.779 32214 32238 E libEGL  : Invalid file path for libcolorx-loader.so

### Yōkai version

1.8.2

### Android version

Android 11

### Device

Realme X (RMS1901)

### Other details

The app was working fine in previous version, after updating to the latest version this issue started, 
1. i tried it by clearing data and restoring backup, it works fine for couple of time then stops working.
2. uninstalled and reinstalled the app then restored backup, it works fine for couple of time then stops working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Hatashiki** [comment] 2024-06-04 18:01
> ### Steps to reproduce
> 1. open the app
> 2. try to download something
> 
> issue: stuck in splash screen or blank screen
> 
> ![yokai stuck in splash or blank screen after update](https://private-user-images.githubusercontent.com/28342175/336332539-44b03be5-18c2-4468-8097-467056b9b619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjQzMDMsIm5iZiI6MTcxNzUyNDAwMywicGF0aCI6Ii8yODM0MjE3NS8zMzYzMzI1MzktNDRiMDNiZTUtMThjMi00NDY4LTgwOTctNDY3MDU2YjliNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE4MDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZDlkNmRmZTJjNmZhN2MwNDA5YjI2NWI5ZmJhYmFhYzg0NGEyMmI0ZDc2NTgyODRhMGU4Yjk4ODYzZjVmYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kAbVsiiB3kXuHAGM_EN7Gd4Dj2gHnziqt88F5n6EFeY)
> 
> ### Expected behavior
> App will open and show the library, and download the selected chapter.
> 
> ### Actual behavior
> stuck in splash screen or blank screen, crashes when download button is selected.
> 
> ### Crash logs
> App version: 1.8.2 (standard, [d0712bd](https://github.com/null2264/yokai/commit/d0712bde73f663b44deeceeee171e8df605ec56c), 129, 2024-06-03T06:51Z) Android version: 11 (SDK 30) Android build ID: RMX1901_11_F.06 Device brand: Realme Device manufacturer: Realme Device name: RMX1901CN Device model: RMX1901 Device product name: RMX1901
> 
> --------- beginning of system 06-04 17:46:36.744 26632 26632 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance --------- beginning of main 06-04 17:51:57.061 26632 26632 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (29757) crash detected (code -1). 06-04 17:52:27.254 26632 26632 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (31495) crash detected (code -1). 06-04 17:52:41.965 26632 27571 E libEGL : Invalid file path for libcolorx-loader.so 06-04 17:52:46.198 26632 32191 E Palette : Exception thrown during async generate 06-04 17:52:46.198 26632 32191 E Palette : java.lang.IllegalStateException: unable to getPixels(), pixel access is not supported on Config#HARDWARE bitmaps 06-04 17:52:46.198 26632 32191 E Palette : at android.graphics.Bitmap.checkHardware(Bitmap.java:445) 06-04 17:52:46.198 26632 32191 E Palette : at android.graphics.Bitmap.getPixels(Bitmap.java:2014) 06-04 17:52:46.198 26632 32191 E Palette : at androidx.palette.graphics.Palette$Builder.generate(SourceFile:3) 06-04 17:52:46.198 26632 32191 E Palette : at androidx.palette.graphics.Palette$Builder$1.doInBackground(SourceFile:5) 06-04 17:52:46.198 26632 32191 E Palette : at android.os.AsyncTask$3.call(AsyncTask.java:394) 06-04 17:52:46.198 26632 32191 E Palette : at java.util.concurrent.FutureTask.run(FutureTask.java:266) 06-04 17:52:46.198 26632 32191 E Palette : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 06-04 17:52:46.198 26632 32191 E Palette : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 06-04 17:52:46.198 26632 32191 E Palette : at java.lang.Thread.run(Thread.java:923) 06-04 17:52:49.042 32214 32214 E i:error_handle: Unknown bits set in runtime_flags: 0x40000000 06-04 17:52:49.048 32214 32214 E i:error_handle: Not starting debugger since process cannot load the jdwp agent. 06-04 17:52:49.052 32214 32214 E RefClass: java.lang.reflect.InvocationTargetException 06-04 17:52:49.078 32214 32214 E libc : Access denied finding property "ro.odm.prev.product.name" 06-04 17:52:49.097 32214 32214 E Perf : perftest packageName : eu.kanade.tachiyomi.yokai Restructing the HIDE apis access to this app, App is not allowed to use Hide APIs : 06-04 17:52:49.187 32214 32240 E libEGL : Invalid file path for libcolorx-loader.so 06-04 17:52:50.769 32214 32238 E libEGL : Invalid file path for libcolorx-loader.so 06-04 17:52:50.776 32214 32238 E libEGL : Invalid file path for libcolorx-loader.so 06-04 17:52:50.779 32214 32238 E libEGL : Invalid file path for libcolorx-loader.so
> 
> ### Yōkai version
> 1.8.2
> 
> ### Android version
> Android 11
> 
> ### Device
> Realme X (RMS1901)
> 
> ### Other details
> The app was working fine in previous version, after updating to the latest version this issue started,
> 
> 1. i tried it by clearing data and restoring backup, it works fine for couple of time then stops working.
> 2. uninstalled and reinstalled the app then restored backup, it works fine for couple of time then stops working.
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
> * [x]  I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
> * [x]  I have tried the [troubleshooting guide](https://mihon.app/help/).
> * [x]  I have updated the app to version **[1.8.2](https://github.com/null2264/yokai/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [ ]  I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
> * [x]  I have filled out all of the requested information in this form.

Yes its happening in many devices. I came to report this and thought its only happened to me but its was a universal problem i think

**Comment by null2264** [comment] 2024-06-04 21:10
> crashes when download button is selected

Did the crash screen didn't pop up? that'd give me much clearer context

**Comment by null2264** [comment] 2024-06-05 00:52
Maybe try 1.8.3, it's a blind shot tho.

**Comment by Hatashiki** [comment] 2024-06-05 02:48
> Maybe try 1.8.3? it's a blind shot tho.

Nah its happening with the same one

**Comment by m-a-hannan** [comment] 2024-06-05 03:50
> > crashes when download button is selected
> 
> Did the crash screen not pop up? if it did pop up, could you screenshot it for me? that'd give me much clearer context

crash screen only apears when download button is selected, start reading or selecting a chater to read  does not work.
Are you asking for this crash screen?

![crash screen](https://github.com/null2264/yokai/assets/28342175/de3ac47a-175e-4b1e-8e93-5d3fb0227343)

**Comment by null2264** [comment] 2024-06-05 03:53
Yep, that screen.

**Comment by YuriHeathcleff** [comment] 2024-06-05 09:02
I got the same problem just for me the left page doesn't even show it's only the right side and it stays like that

**Comment by tuskk** [comment] 2024-06-05 09:04
https://github.com/null2264/yokai/assets/85387302/f50966d2-ff8b-460b-816b-0438a59337b5

**Comment by YuriHeathcleff** [comment] 2024-06-05 09:27
> screen-20240605-110204.mp4

Mine is also kinda like that but where ur screen gets a little Gray mine stops there and doesn't do anything else like enter the app then it gets a little gray-ish and stays like that

**Comment by tuskk** [comment] 2024-06-05 10:18
> Mine is also kinda like that but where ur screen gets a little Gray mine stops there and doesn't do anything else like enter the app then it gets a little gray-ish and stays like that

Mine kinda boot looping with black and gray screen and loop library update

**Comment by YuriHeathcleff** [comment] 2024-06-05 10:25
> > Mine is also kinda like that but where ur screen gets a little Gray mine stops there and doesn't do anything else like enter the app then it gets a little gray-ish and stays like that
> 
> Mine kinda boot looping with black and gray screen and loop library update
> 
> (Google pixel 6a android 14)

Bruh I didn't even backup before updating now I lost almost 15 days worth of data

**Comment by tuskk** [comment] 2024-06-05 10:30
> Bruh I didn't even backup before updating now I lost almost 15 days worth of data
> 

Nah ma man its nothing in comparison when i start using yokai after tachi i lose 1.5 year of progress

**Comment by m-a-hannan** [comment] 2024-06-05 11:37
> > Bruh I didn't even backup before updating now I lost almost 15 days worth of data
> 
> Nah ma man its nothing in comparison when i start using yokai after tachi i lose 1.5 year of progress

Didn't you use auto backup? 
Mine was set to take backup daily. But for some reason auto backup didn't work after 27th may.

**Comment by YuriHeathcleff** [comment] 2024-06-05 11:39
> > > Bruh I didn't even backup before updating now I lost almost 15 days worth of data
> > 
> > 
> > Nah ma man its nothing in comparison when i start using yokai after tachi i lose 1.5 year of progress
> 
> Didn't you use auto backup? Mine was set to take backup daily. But for some reason auto backup didn't work after 27th may.

I did auto backup every 12 hours but it doesn't work idk why

**Comment by YuriHeathcleff** [comment] 2024-06-05 11:40
> > > > Bruh I didn't even backup before updating now I lost almost 15 days worth of data
> > > 
> > > 
> > > Nah ma man its nothing in comparison when i start using yokai after tachi i lose 1.5 year of progress
> > 
> > 
> > Didn't you use auto backup? Mine was set to take backup daily. But for some reason auto backup didn't work after 27th may.
> 
> I did auto backup every 12 hours but it doesn't work idk why

Isn't it just the timer for auto backup? Cause idk if there's something I didn't do

**Comment by tuskk** [comment] 2024-06-05 11:40
> > > > Bruh I didn't even backup before updating now I lost almost 15 days worth of data
> > > 
> > > 
> > > Nah ma man its nothing in comparison when i start using yokai after tachi i lose 1.5 year of progress
> > 
> > Didn't you use auto backup? Mine was set to take backup daily. But for some reason auto backup didn't work after 27th may.
> 
> I did auto backup every 12 hours but it doesn't work idk why 

Same here

**Comment by YuriHeathcleff** [comment] 2024-06-05 11:42
> > > > > Bruh I didn't even backup before updating now I lost almost 15 days worth of data
> > > > 
> > > > 
> > > > Nah ma man its nothing in comparison when i start using yokai after tachi i lose 1.5 year of progress
> > > 
> > > 
> > > Didn't you use auto backup? Mine was set to take backup daily. But for some reason auto backup didn't work after 27th may.
> > 
> > 
> > I did auto backup every 12 hours but it doesn't work idk why
> 
> Same here

Oof that hurts i wasn't the only one it seems like now I have to stay here in hopes of them releasing a new update that hopefully fixes the problem we have

**Comment by null2264** [comment] 2024-06-05 11:54
Reopening, GitHub false positive

**Comment by YuriHeathcleff** [comment] 2024-06-05 11:55
How do I fix it then please explain I'm dumb

**Comment by YuriHeathcleff** [comment] 2024-06-05 11:57
> Reopening, GitHub false positive

Oo mb so the problem still not solved huh

**Comment by null2264** [comment] 2024-06-05 12:07
Yeah, I'm still figuring out the issue. For now, you can try updating to [1.8.3.1](https://github.com/null2264/yokai/releases/tag/v1.8.3.1).

**Comment by YuriHeathcleff** [comment] 2024-06-05 12:16
> Yeah, I'm still figuring out the issue. For now, you can try updating to [1.8.3.1](https://github.com/null2264/yokai/releases/tag/v1.8.3.1).

Sadly it still doesn't work and with me even the error report doesn't appear but thanks for trying tho

**Comment by null2264** [comment] 2024-06-06 01:06
I improved "error catcher" on [1.8.3.3](https://github.com/null2264/yokai/releases/tag/v1.8.3.3), hopefully that'll help me figure out what the hell happened, you can try triggering the error on that version...

**Comment by m-a-hannan** [comment] 2024-06-06 01:38
> I improved "error catcher" on [1.8.3.3](https://github.com/null2264/yokai/releases/tag/v1.8.3.3), hopefully that'll help me figure out what the hell happened, you can try triggering the error on that version...

1.8.3.3 fixed the issues for me. Thank you 🤝.

**Comment by null2264** [comment] 2024-06-06 01:41
Well that's strange... I technically didn't do anything to the app, just improving how it reports error ._.

But I'm glad that helps. I'll keep this issue open for now, in case the issue is back.

**Comment by Nanamiwaifu** [comment] 2024-06-06 02:40
Still doesn't work on mine. App keeps stopping. Doesn't even load. Is there something I could do to make it work like uninstall and reinstall or something? Someone please help!

**Comment by m-a-hannan** [comment] 2024-06-06 02:45
> Well that's strange... I technically didn't do anything to the app, just improving how it reports error ._.
> 
> But I'm glad that helps. I'll keep this issue open for now, in case the issue is back.

Strange indeed...!!! 🤯🤯😵

**Comment by YuriHeathcleff** [comment] 2024-06-06 03:27
> I improved "error catcher" on [1.8.3.3](https://github.com/null2264/yokai/releases/tag/v1.8.3.3), hopefully that'll help me figure out what the hell happened, you can try triggering the error on that version...

Works for 2 seconds lol

**Comment by null2264** [comment] 2024-06-06 03:28
RIP

**Comment by null2264** [comment] 2024-06-06 03:31
I've tried to fix most of the crashes I detected on v1.8.3.3 on [v1.8.3.4](https://github.com/null2264/yokai/releases/tag/v1.8.3.4)... hopefully it's fixed frfr this time.

**Comment by YuriHeathcleff** [comment] 2024-06-06 03:32
> I've tried to fix most of the crashes I detected on v1.8.3.3 on [v1.8.3.4](https://github.com/null2264/yokai/releases/tag/v1.8.3.4)... hopefully it's fixed frfr this time.

Really hope

**Comment by YuriHeathcleff** [comment] 2024-06-06 03:36
> I've tried to fix most of the crashes I detected on v1.8.3.3 on [v1.8.3.4](https://github.com/null2264/yokai/releases/tag/v1.8.3.4)... hopefully it's fixed frfr this time.

Yo bro I have a request can you somehow fix the auto backup thing it doesn't work for me but thank you so much. For fixing this now it works for me thanks a lot I would've treated U to a meal if I had known you thanks a lot

**Comment by null2264** [comment] 2024-06-06 03:41
> fix the auto backup thing

I'd recommend you to try turning it off then turn it back on first to see if that helps, sometime it refuses to work when it refuses to "wake up" when the job is interrupted, also happened to me but with auto extension update instead... as far as I know it's an Android thing, but I'll see if I can workaround it

**Comment by YuriHeathcleff** [comment] 2024-06-06 03:44
> > fix the auto backup thing
> 
> I'd recommend you to try turning it off then turn it back on first to see if that helps, sometime it refuses to work when it refuses to "wake up" when the job is interrupted, also happened to me but with auto extension update instead... as far as I know it's an Android thing, but I'll see if I can workaround it

Nah bro uve done more than enough thanks for everything 🫡

**Comment by YuriHeathcleff** [comment] 2024-06-06 03:49
> > fix the auto backup thing
> 
> I'd recommend you to try turning it off then turn it back on first to see if that helps, sometime it refuses to work when it refuses to "wake up" when the job is interrupted, also happened to me but with auto extension update instead... as far as I know it's an Android thing, but I'll see if I can workaround it

But would you recommend using yokai still or switching to MIHON im not sure still I like the interface of yokai I just don't wanna switch to MIHON unless it's totally necessary

**Comment by null2264** [comment] 2024-06-06 04:00
> But would you recommend using yokai still or switching to MIHON im not sure still I like the interface of yokai I just don't wanna switch to MIHON unless it's totally necessary

That's entirely up to you, I'm actually developing yokai for myself since J2K is on halt and thought it'd be a great hobby project since I personally love Kotlin.

Personally, I'd recommend everyone to migrate to Mihon (or back to J2K, if you like his UI design) since I couldn't guarantee to not f\*ck up and potentially cause everyone to lost your entire Tachi data, since J2K has lots of tech debt that basically like an abandon landmine(s) that could explode if I touch it the wrong way trying to modernize it. Also, updates will be sporadic, sometimes fast (like it is at the moment), sometimes takes a couple of month... So yeah, your choice...

But if you decided to stay, I appreciate you for having the patient to deal with my sh*t... ._.

**Comment by YuriHeathcleff** [comment] 2024-06-06 04:05
> > But would you recommend using yokai still or switching to MIHON im not sure still I like the interface of yokai I just don't wanna switch to MIHON unless it's totally necessary
> 
> That's entirely up to you, I'm actually developing yokai for myself since J2K is on halt and thought it'd be a great hobby project since I personally love Kotlin (not as much as Elixir tho, if you know what I'm talking about :v).
> 
> Personally, I'd recommend everyone to migrate to Mihon (or back to J2K, if you like his UI design) since I couldn't guarantee to not f*ck up and potentially cause everyone to lost your entire Tachi data, since J2K has lots of tech debt that basically like an abandon landmine(s) that could explode if I touch it the wrong way trying to modernize it. Also, updates will be sporadic, sometimes fast (like it is at the moment), sometimes takes a couple of month... So yeah, your choice...
> 
> But if you decided to stay, I appreciate you for having the patient to deal with my sh*t... ._.

I don't mind the update delays bro I just wanna know one thing that will it stop working like with a big android update like we were once told because now I just gotta remember to turn on and off auto backup that's all I just need to know whether I will be able to use it long term that's all because I got like a few thousand entries in my yokai and Im too used to reading in yokai I just don't like mihons interface if it was the same as yokai or j2k then there would've been no problem from me lol still thanks for all da hard work bro

**Comment by null2264** [comment] 2024-06-06 04:09
> I don't mind the update delays bro I just wanna know one thing that will it stop working like with a big android update like we were once told because now I just gotta remember to turn on and off auto backup that's all I just need to know whether I will be able to use it long term that's all because I got like a few thousand entries in my yokai and Im too used to reading in yokai I just don't like mihons interface if it was the same as yokai or j2k then there would've been no problem from me lol still thanks for all da hard work bro

Should still be working fine as long as I update it yeah.

**Comment by YuriHeathcleff** [comment] 2024-06-06 04:10
> > I don't mind the update delays bro I just wanna know one thing that will it stop working like with a big android update like we were once told because now I just gotta remember to turn on and off auto backup that's all I just need to know whether I will be able to use it long term that's all because I got like a few thousand entries in my yokai and Im too used to reading in yokai I just don't like mihons interface if it was the same as yokai or j2k then there would've been no problem from me lol still thanks for all da hard work bro
> 
> Should still be working fine as long as I update it yeah.

If so then well I'm staying lol and thanks for the hard work and good luck yeay

**Comment by null2264** [comment] 2024-06-07 02:11
Closing this as there doesn't seem to be any new report, feel free to open a new issue if the issue reappear.

**Closed by null2264** 2024-06-07 02:11 UTC
Labels: bug
