### ISSUE TITLE
Manga recommendations

### ISSUE THREAD

**Issue by Ejobat** [null2264/yokai#148] opened 2024-08-11 02:55 UTC
### Describe your suggested feature

This feature is available in TachiyomiSY. It uses MyAnimeList (MAL) and Anilist, as well as Neko Similar Manga for Mangadex manga. 

I think this feature will significantly improve this app.

![Screenshot_20240811-055158~2](https://github.com/user-attachments/assets/6d3d609d-9b6c-4127-b42f-a0541e1c8433)
![Screenshot_20240811-055220~2](https://github.com/user-attachments/assets/70c160b8-1d49-4b62-8a9e-b5c8611d7ded)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.4.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment] 2024-08-12 00:57
Duplicate of issue mentioned above

**Closed by null2264** 2024-08-12 00:57 UTC
Labels: enhancement
