### ISSUE TITLE
Sorting by later chapter broken

### ISSUE THREAD

**Issue by TheHighKingGama** [null2264/yokai#313] opened 2024-12-20 08:00 UTC
### Steps to reproduce

Have sort of options selected by latest chapter update Library to find sorting not working correctly

### Expected behavior

When sorting the library should be showing series with recent uploads first

### Actual behavior

When sorting the library it shows some series that haven't been updated in days to even years on top of list
![Screenshot_20241220_015118_Ykai](https://github.com/user-attachments/assets/02f913b2-8833-4abd-a946-3b12831b1b68)
![Screenshot_20241220_015122_Ykai](https://github.com/user-attachments/assets/270c6de7-4de0-4b80-8798-e5552e4e4948)
![Screenshot_20241220_015030_Ykai](https://github.com/user-attachments/assets/3f4cbf45-fa1c-48a0-9bb4-14e1df83afc1)

### Yōkai version

App version: 1.9.6 (standard, 6c40fe92be, 156, 2024-12-17T23:11:43Z) Android version: 14 (SDK 34) Android build ID: UP1A.231005.007.S928WVLS4AXKA Device brand: samsung Device manufacturer: samsung Device name: e3q Device model: SM-S928W Device product name: e3qcsx

### Android version

Android 14

### Device

samsung galaxy s24ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment] 2024-12-20 11:45
Duplicate of GH-309

**Closed by null2264** 2024-12-20 11:45 UTC
Labels: bug
