### ISSUE TITLE
"Open in website" loads an API instead of the actual website

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#226] opened 2024-10-12 12:06 UTC
### Steps to reproduce

Open Kemono extension by [Keiyoushi](https://keiyoushi.github.io/extensions/)
Open an artist's page
Long press a chapter
Click "Open in website"

### Expected behavior

Should open the website

### Actual behavior

![Screenshot_20241012_060318_Ykai Nightly](https://github.com/user-attachments/assets/2da3398c-b208-4d55-88fc-b04d8703795e)

### Yōkai version

App version: 1.8.5.9-r5767 (standard, 6ba22b9e45, 149, 2024-10-10T03:26:41Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXSGHWA3 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2ltexx

### Android version

12

### Device

S10+

### Other details

I'm not sure if this is a Yokai's thing or Keiyoushi's, but it seems Yokai's most likely

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment] 2024-10-13 05:22
Work as intended for chapters, need to be fixed on extension side.

**Closed by null2264** 2024-10-13 05:22 UTC
Labels: bug
